# Site Settings
locale: "en-US"
title: "Pankhuri Kulshrestha"
title_separator: " | "
name: "Pankhuri Kulshrestha"
description: "Machine Learning Research Engineer"
url: "https://panks11.github.io"
baseurl: "/pankhuri"
github_username: panks11

# Theme skin (disable theme toggle by using only one skin)
skin: "default"

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

# Site Author
author:
  name: "Pankhuri Kulshrestha"
  avatar: "profile.png"
  bio: "Machine Learning Research Engineer"
  location: "Manchester, UK"
  email: "kulshrestha.pankhuri@gmail.com"
  linkedin: "pankhuri-kulshrestha-20a65917"
  github: "panks11"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sidebar settings
sidebar:
  nav: "main"

# Navigation
main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Experience"
    url: /experience/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /projects/
